apiVersion: v1
kind: Secret
metadata:
  namespace: droneci
  name: drone-server-secret
type: Opaque
data:
  # all base64
  # Get this from GitHub OAUTH
  DRONE_GITHUB_CLIENT_ID: YmVhOTU3ZjAzMzkyYjc2YjJlYTQ=  
  DRONE_GITHUB_CLIENT_SECRET: ZTZkMzI3NGI1ZWFhYzZkYWUyYTVlYWVjNTdlYTg3YWQ0YTQwZDQ0Ng==
  # openssl rand -hex 16
  DRONE_RPC_SECRET: OTZkMjdjYzNlZWVmYjhkNTI2NzgyYzgzM2QyMGIwZDY=
  # postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_DATABASE_DATASOURCE: cG9zdGdyZXM6Ly9wb3N0Z3Jlc2FkbWluOmFkbWluMTIzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXNkYj9zc2xtb2RlPWRpc2FibGU=
  # username:james426759,admin:true
  DRONE_USER_CREATE: dXNlcm5hbWU6amFtZXM0MjY3NTksYWRtaW46dHJ1ZQ==
  # james.nutc-imac.com
  DRONE_SERVER_HOST: amFtZXMubnV0Yy1pbWFjLmNvbQ==