apiVersion: v1
kind: Service
metadata:
  namespace: droneci
  name: droneserver
  labels:
    app: drone-server
spec:
  type: NodePort
  selector:
    app: drone-server
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30010
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
      nodePort: 30011